#!/bin/bash

##############################################################################
#                                                                            #
#     Combining the ssh connection and pass through for a vnc viewer         #
#     with the launch of a vnc viewer.                                       #
#                                                                            #
#     Three environment variables are required but one of them has a         #
#     value:                                                                 #
#                                                                            #
#         VNCVIEWER   The vnc viewer program. Defaults to xtigervncviewer    #
#         CONNECTION  The ssh command used to reach the gateway machine      #
#         TARGET      The machine hosting the ssh proxy                      #
#                                                                            #
#                                                                            #
#    Since the viewer depends upon a running CONNECTION a shell script       #
#    is crafted inline with this script which waits a few seconds before     #
#    launching the viewer. This wait runs in the background and does not     #
#    block this script.                                                      #
#                                                                            #
#    Then the script runs the CONNECTION command establishin the ssh proxy   #
#    the viewer will use before th viewer tris to use it.                    #
#                                                                            #
##############################################################################

VNC_CMDFILE=run_vnc
[ -f variables ] && source variables
[ -d /tmp ] && cd /tmp

ERRMSG_0="No CONNECTION specified."
ERRMSG_1="No vnc host specified."
VIEWER=${VNCVIEWER:=xtigervncviewer}
GATEWAY=${CONNECTION:-$ERRMSG_0}
HOST=${TARGET:-$ERRMSG_1}
TIMEOUT=${TIMEOUT:=8}
LOGFILE=log.run_vnc

build_vnc_cmd()
{
        rm -f $VNC_CMDFILE
        cat  > $VNC_CMDFILE << EOF
#!/bin/bash
CMD_VNC="$VIEWER $HOST"
export VNC_PASSWORD=$VNC_PASSWORD

# Sleep a bit to give the caller time
# to set up the ssh tunnel
#
sleep $TIMEOUT

# escape the '$' so that the substition happens at runtime
# not at create time. I.E. CMD_VNC only has meaning once the
# file is written out and run.
#
\$CMD_VNC > $LOGFILE 2>&1

# Remove ourself from existence. The inode will live until we're done.
rm \$0
EOF
        chmod +x $VNC_CMDFILE
}

# Write a script out to a file
build_vnc_cmd

# run the script in its own procss group disconnected
# from any stdout/stdin/stderr file descriptors so it
# wont block waiting for keyboard data.
#
setsid -f ./$VNC_CMDFILE

# Establish the ssh tunnl to the gateway which opens a shell command line
#
eval $GATEWAY

